name: Git State
description: Detect Git state including PR context, open PRs for the current branch, and source/target branch names

outputs:
  is-pull-request:
    description: "true if running on pull_request event (GITHUB_HEAD_REF is set), false for push events"
    value: ${{ steps.out.outputs.is-pull-request }}
  ci-open-pull-request:
    description: "true if an open PR exists for the current branch (always true for PR events, queried via API for push events)"
    value: ${{ steps.out.outputs.ci-open-pull-request }}
  source-branch-name:
    description: "Source branch name (GITHUB_HEAD_REF for PR events, GITHUB_REF_NAME for push events)"
    value: ${{ steps.out.outputs.source-branch-name }}
  target-branch-name:
    description: "Target/base branch name (GITHUB_BASE_REF for PR events, empty for push events)"
    value: ${{ steps.out.outputs.target-branch-name }}

runs:
  using: "composite"
  steps:
    - name: Check if branch has open PR
      id: out
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        set -euo pipefail

        OWNER="${GITHUB_REPOSITORY%%/*}"
        REPO="${GITHUB_REPOSITORY##*/}"        
        
        # Detect PR runs by ref format
        if [[ -n "${GITHUB_HEAD_REF:-}" ]]; then
          echo "is-pull-request=true" >> "$GITHUB_OUTPUT"
          echo "ci-open-pull-request=true" >> "$GITHUB_OUTPUT" 
          echo "source-branch-name=$GITHUB_HEAD_REF" >> "$GITHUB_OUTPUT"
          echo "target-branch-name=$GITHUB_BASE_REF" >> "$GITHUB_OUTPUT"
          echo "- [x] is-pull-request">> "$GITHUB_STEP_SUMMARY"
          echo "- [x] ci-open-pull-request (current event, is pull_request)" >> "$GITHUB_STEP_SUMMARY"
          echo "- [x] source-branch-name: $GITHUB_HEAD_REF" >> "$GITHUB_STEP_SUMMARY"
          echo "- [x] target-branch-name: $GITHUB_BASE_REF" >> "$GITHUB_STEP_SUMMARY"        
          exit 0
        fi 
        
        # Push runs
        BRANCH="${GITHUB_REF_NAME}"
        echo "is-pull-request=false" >> "$GITHUB_OUTPUT"
        echo "source-branch-name=$BRANCH" >> "$GITHUB_OUTPUT"
        echo "target-branch-name=" >> "$GITHUB_OUTPUT"
        
        # Count open PRs for this branch (same-repo branches)
        set +e
        COUNT="$(gh api graphql -f query='
          query($owner:String!, $name:String!, $head:String!) {
            repository(owner:$owner, name:$name) {
              pullRequests(states:OPEN, headRefName:$head) { totalCount }
            }
          }' \
          -f owner="$OWNER" -f name="$REPO" -f head="$BRANCH" \
          --jq '.data.repository.pullRequests.totalCount' 2>&1)"
        API_STATUS=$?
        set -e

        if [[ $API_STATUS -ne 0 ]] || [[ -z "$COUNT" ]] || [[ ! "$COUNT" =~ ^[0-9]+$ ]]; then
          echo "::warning::Failed to query GitHub API for open PRs (status: $API_STATUS). Assuming no open PRs exist."
          COUNT="0"
        fi

        echo "- [ ] is-pull-request">> "$GITHUB_STEP_SUMMARY"
        if [[ "$COUNT" == "0" ]]; then
          echo "ci-open-pull-request=false"  >> "$GITHUB_OUTPUT"
          echo "- [ ] ci-open-pull-request (no PR for the same branch detected)" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "ci-open-pull-request=true" >> "$GITHUB_OUTPUT"
          echo "- [X] ci-open-pull-request (PR for the same branch detected)" >> "$GITHUB_STEP_SUMMARY"        
        fi
        echo "- [x] source-branch-name: $BRANCH" >> "$GITHUB_STEP_SUMMARY"
        echo "- [x] target-branch-name: -" >> "$GITHUB_STEP_SUMMARY"
