name: Git PR Exists
description: Detect whether the current branch already has an open pull request

outputs:
  is-pull-request:
    description: "true if GITHUB_REF looks like refs/pull/<nr>/..., else false"
    value: ${{ steps.out.outputs.is-pull-request }}
  ci-open-pull-requests:
    description: "true if there is an open PR for this branch (push runs), else false"
    value: ${{ steps.out.outputs.ci-open-pull-request }}
  branch:
    description: "branch name if push; empty for PR merge refs"
    value: ${{ steps.out.outputs.branch }}

runs:
  using: "composite"
  steps:
    - name: Check if branch has open PR
      id: out
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        set -euo pipefail
        
        REF="${GITHUB_REF}"
        OWNER="${GITHUB_REPOSITORY%%/*}"
        REPO="${GITHUB_REPOSITORY##*/}"        
        
        # Detect PR runs by ref format
        if [[ "$REF" =~ ^refs/pull/([0-9]+)/ ]]; then
          echo "is-pull-request=true" >> "$GITHUB_OUTPUT"
          echo "ci-open-pull-request=true" >> "$GITHUB_OUTPUT" 
          echo "branch=" >> "$GITHUB_OUTPUT"
          echo "- [x] ci-open-pull-requests=true (current event, is pull_request)" >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi      
        
        # Push runs
        BRANCH="${GITHUB_REF_NAME}"
        echo "is-pull-request=false" >> "$GITHUB_OUTPUT"
        echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"
        
        # Count open PRs for this branch (same-repo branches)
        COUNT="$(gh api graphql -f query='
          query($owner:String!, $name:String!, $head:String!) {
            repository(owner:$owner, name:$name) {
              pullRequests(states:OPEN, headRefName:$head) { totalCount }
            }
          }' \
          -f owner="$OWNER" -f name="$REPO" -f head="$BRANCH" \
          --jq '.data.repository.pullRequests.totalCount')"     
        
        if [[ "$COUNT" == "0" ]]; then
          echo "ci-open-pull-requests=false"  >> "$GITHUB_OUTPUT"
          echo "- [ ] ci-open-pull-requests=false (no PR for the same branch detected)" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "ci-open-pull-requests=true" >> "$GITHUB_OUTPUT"
          echo "- [X] ci-open-pull-requests=true (PR for the same branch detected)" >> "$GITHUB_STEP_SUMMARY"        
        fi
