name: Git State
description: Detect Git state including PR context, open PRs for the current branch, and source/target branch names

inputs:
  ci-release-branch-patterns:
    description: "Comma-separated branch patterns to identify release branches (e.g., 'main,release/*')"
    required: false
    default: "main"

outputs:
  is-release-branch:
    description: "true if the target branch (PR) or current branch (push) matches ci-release-branch-patterns"
    value: ${{ steps.out.outputs.is-release-branch }}
  has-open-pull-requests:
    description: "true if an open PR exists for the current branch (always true for PR events, queried via API for push events)"
    value: ${{ steps.out.outputs.has-open-pull-requests }}
  source-branch-name:
    description: "Source branch name (GITHUB_HEAD_REF for PR events, GITHUB_REF_NAME for push events)"
    value: ${{ steps.out.outputs.source-branch-name }}
  target-branch-name:
    description: "Target/base branch name (GITHUB_BASE_REF for PR events, empty for push events)"
    value: ${{ steps.out.outputs.target-branch-name }}

runs:
  using: "composite"
  steps:
    - name: Check if branch has open PR
      id: out
      env:
        GH_TOKEN: ${{ github.token }}
        RELEASE_PATTERNS: ${{ inputs.ci-release-branch-patterns }}
      shell: bash
      run: |
        set -euo pipefail

        matches_pattern() {
          local branch="$1"
          local patterns="$2"

          IFS=',' read -ra PATTERNS <<< "$patterns"
          for pattern in "${PATTERNS[@]}"; do
            pattern=$(echo "$pattern" | xargs)
            if [[ "$branch" == $pattern ]]; then
              return 0
            fi
          done
          return 1
        }

        OWNER="${GITHUB_REPOSITORY%%/*}"
        REPO="${GITHUB_REPOSITORY##*/}"

        # Detect PR runs by ref format
        if [[ -n "${GITHUB_HEAD_REF:-}" ]]; then
          if matches_pattern "$GITHUB_BASE_REF" "$RELEASE_PATTERNS"; then
            IS_RELEASE_BRANCH="true"
          else
            IS_RELEASE_BRANCH="false"
          fi

          echo "is-release-branch=$IS_RELEASE_BRANCH" >> "$GITHUB_OUTPUT"
          echo "has-open-pull-requests=true" >> "$GITHUB_OUTPUT"
          echo "source-branch-name=$GITHUB_HEAD_REF" >> "$GITHUB_OUTPUT"
          echo "target-branch-name=$GITHUB_BASE_REF" >> "$GITHUB_OUTPUT"
          {
            echo "### git-state"
            echo "- Event type: \`pull_request\`"
            echo "- Is release branch: \`$IS_RELEASE_BRANCH\`"
            echo "- Has open pull requests: \`true\`"
            echo "- Source branch: \`$GITHUB_HEAD_REF\`"
            echo "- Target branch: \`$GITHUB_BASE_REF\`"
          } >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi 
        
        # Push runs
        BRANCH="${GITHUB_REF_NAME}"

        if matches_pattern "$BRANCH" "$RELEASE_PATTERNS"; then
          IS_RELEASE_BRANCH="true"
        else
          IS_RELEASE_BRANCH="false"
        fi

        echo "source-branch-name=$BRANCH" >> "$GITHUB_OUTPUT"
        echo "target-branch-name=" >> "$GITHUB_OUTPUT"
        echo "is-release-branch=$IS_RELEASE_BRANCH" >> "$GITHUB_OUTPUT"        
        
        # Count open PRs for this branch (same-repo branches)
        set +e
        COUNT="$(gh api graphql -f query='
          query($owner:String!, $name:String!, $head:String!) {
            repository(owner:$owner, name:$name) {
              pullRequests(states:OPEN, headRefName:$head) { totalCount }
            }
          }' \
          -f owner="$OWNER" -f name="$REPO" -f head="$BRANCH" \
          --jq '.data.repository.pullRequests.totalCount' 2>&1)"
        API_STATUS=$?
        set -e

        if [[ $API_STATUS -ne 0 ]] || [[ -z "$COUNT" ]] || [[ ! "$COUNT" =~ ^[0-9]+$ ]]; then
          echo "::warning::Failed to query GitHub API for open PRs (status: $API_STATUS). Assuming no open PRs exist."
          COUNT="0"
        fi

        if [[ "$COUNT" == "0" ]]; then
          echo "has-open-pull-requests=false"  >> "$GITHUB_OUTPUT"
          HAS_PR="false"
        else
          echo "has-open-pull-requests=true" >> "$GITHUB_OUTPUT"
          HAS_PR="true"
        fi

        {
          echo "### git-state"
          echo "- Event type: \`push\`"
          echo "- Is release branch: \`$IS_RELEASE_BRANCH\`"
          echo "- Has open pull requests: \`$HAS_PR\`"
          echo "- Source branch: \`$BRANCH\`"
          echo "- Target branch: \`-\`"
        } >> "$GITHUB_STEP_SUMMARY"
