name: Git PR Exists
description: Detect whether the current branch already has an open pull request

inputs:
  github-token:
    description: Token with `repo` scope used to call the GitHub pull request API.
    required: false
    default: ''

outputs:
  exists:
    description: "'true' if any open pull requests target the current branch"
    value: ${{ steps.pull_request.outputs.exists }}
  count:
    description: Number of matching open pull requests
    value: ${{ steps.pull_request.outputs.count }}
  ci-open-pull-requests:
    description: "Backwards compatible alias for `exists`"
    value: ${{ steps.pull_request.outputs.exists }}

runs:
  using: "composite"
  steps:
    - name: Check if branch has open PR
      id: pull_request
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token != '' && inputs.github-token || github.token }}
        GH_TOKEN: ${{ inputs.github-token != '' && inputs.github-token || github.token }}
      run: |
        set -euo pipefail

        token="${GITHUB_TOKEN:-${GH_TOKEN:-}}"
        if [ -z "$token" ]; then
          echo "::notice::PR existence verification skipped, no github-token provided"
          {
            echo "exists=false"
            echo "count=0"
          } >> "$GITHUB_OUTPUT"
          exit 0
        fi

        branch="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME:-}}"
        if [ -z "$branch" ]; then
          echo "Unable to determine branch name" >&2
          exit 1
        fi

        repo="${GITHUB_REPOSITORY}"
        owner="${repo%%/*}"

        prs=$(gh pr list \
          --repo "$repo" \
          --state open \
          --head "${owner}:${branch}" \
          --json number \
          --jq 'length')

        prs="${prs:-0}"

        if [ "$prs" -gt 0 ]; then
          exists=true
        else
          exists=false
        fi

        {
          echo "exists=$exists"
          echo "count=$prs"
        } >> "$GITHUB_OUTPUT"
