name: node-js-version-reader
description: Read version from package.json and emit it.

outputs:
  version:
    description: "Version read from package.json"
    value: ${{ steps.read.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Read package.json version
      id: read
      shell: bash
      run: |
        set -euo pipefail
        FILE="package.json"
        if [ ! -f "$FILE" ]; then
          echo "::error::package.json not found at $FILE"
          exit 1
        fi

        VERSION=$(node -e "const fs=require('fs');const pkg=JSON.parse(fs.readFileSync(process.argv[1],'utf8'));const version=(pkg.version||'').toString().trim();if(!version){process.exit(3);}console.log(version);" "$FILE" 2>/tmp/node-error || true)
        STATUS=$?
        if [ $STATUS -ne 0 ]; then
          echo "::error::Failed to read version from $FILE"
          cat /tmp/node-error >&2 || true
          exit 1
        fi

        echo "::notice::$FILE version: $VERSION"
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        {
          echo "### node-js-version"
          echo "- Version: $VERSION"
        } >> "$GITHUB_STEP_SUMMARY"
