name: Version Reader
description: Read version information from Node.js package.json, Flutter pubspec.yaml, or read latest version tag from ci branch

inputs:
  type:
    description: "Source type to read version from. Supported values: nodejs, flutter, branch"
    required: true
  branch:
    description: "Branch name to read latest tag from (required when type=branch)"
    required: true

outputs:
  version:
    description: "Full version string with optional postfix (e.g., v1.0.1+1, 1.0.1)"
    value: ${{ steps.read.outputs.version }}
  version-short:
    description: "Clean semantic version without postfix (e.g., v1.0.1, 1.0.1)"
    value: ${{ steps.read.outputs.version_short }}
  title:
    description: "Project title from package.json name field (nodejs only)"
    value: ${{ steps.read.outputs.title }}
  description:
    description: "Project description from package.json description field (nodejs only)"
    value: ${{ steps.read.outputs.description }}

runs:
  using: "composite"
  steps:
    - name: Read version
      id: read
      shell: bash
      run: |
        set -euo pipefail

        TYPE="${{ inputs.type }}"

        if [[ "$TYPE" == "nodejs" ]]; then
          echo "::notice::Reading version from package.json"

          if [ ! -f "package.json" ]; then
            echo "::error::package.json not found in repository root"
            exit 1
          fi

          VERSION=$(jq -r '.version // empty' package.json)

          if [ -z "$VERSION" ]; then
            echo "::error::No version field found in package.json"
            exit 1
          fi

          TITLE=$(jq -r '.name // empty' package.json)
          DESCRIPTION=$(jq -r '.description // empty' package.json)

          echo "::notice::Read version from package.json: $VERSION"

          if [ -n "$TITLE" ]; then
            echo "title=$TITLE" >> "$GITHUB_OUTPUT"
            echo "::notice::Read title from package.json: $TITLE"
          fi

          if [ -n "$DESCRIPTION" ]; then
            echo "description=$DESCRIPTION" >> "$GITHUB_OUTPUT"
            echo "::notice::Read description from package.json: $DESCRIPTION"
          fi

        elif [[ "$TYPE" == "flutter" ]]; then
          echo "::notice::Reading version from pubspec.yaml"

          if [ ! -f "pubspec.yaml" ]; then
            echo "::error::pubspec.yaml not found in repository root"
            exit 1
          fi

          VERSION=$(grep -E "^version:" pubspec.yaml | sed 's/version:[[:space:]]*//' | tr -d '\r' | xargs)

          if [ -z "$VERSION" ]; then
            echo "::error::No version field found in pubspec.yaml"
            exit 1
          fi

          echo "::notice::Read version from pubspec.yaml: $VERSION"

        elif [[ "$TYPE" == "branch" ]]; then
          echo "::notice::Reading latest version tag from ci branch"

          BRANCH="${{ inputs.branch }}"

          if [[ -z "$BRANCH" ]]; then
            echo "::error::branch input is required when type=branch"
            exit 1
          fi

          echo "::notice::Branch: $BRANCH"

          git fetch --tags --force >/dev/null 2>&1 || true

          LATEST_TAG=""
          if git rev-parse "origin/$BRANCH" >/dev/null 2>&1; then
            RAW_TAGS=$(git tag --merged "origin/$BRANCH" 2>/dev/null || true)

            SEMVER_TAGS=""
            if [ -n "$RAW_TAGS" ]; then
              while IFS= read -r TAG; do
                [ -z "$TAG" ] && continue

                if [[ "$TAG" =~ ^([vV]?)([0-9]+)\.([0-9]+)\.([0-9]+)(\+.+)?$ ]]; then
                  TAG_PREFIX="${BASH_REMATCH[1]}"
                  TAG_MAJOR="${BASH_REMATCH[2]}"
                  TAG_MINOR="${BASH_REMATCH[3]}"
                  TAG_PATCH="${BASH_REMATCH[4]}"

                  TAG_BASE="${TAG_MAJOR}.${TAG_MINOR}.${TAG_PATCH}"
                  SEMVER_TAGS+="$TAG_BASE\n"
                fi
              done <<< "$RAW_TAGS"
            fi

            if [ -n "$SEMVER_TAGS" ]; then
              LATEST_BASE=$(printf '%s\n' "$SEMVER_TAGS" | sed '/^$/d' | sort -V | tail -n1)
              # Get the original tag to preserve prefix and postfix
              LATEST_TAG=$(git tag --merged "origin/$BRANCH" | grep -E "^[vV]?${LATEST_BASE}" | head -n1)
            fi
          else
            echo "::warning::Branch origin/$BRANCH not found"
          fi

          if [ -z "$LATEST_TAG" ]; then
            VERSION="0.0.0"
            echo "::notice::No tags found on ci branch, using default: $VERSION"
          else
            VERSION="$LATEST_TAG"
            echo "::notice::Latest tag from ci branch: $VERSION"
          fi

        else
          echo "::error::Unsupported type: $TYPE"
          echo "::error::Supported types: nodejs, flutter, branch"
          exit 1
        fi

        # Validate version matches supported patterns
        if [[ ! "$VERSION" =~ ^([vV]?)([0-9]+)\.([0-9]+)\.([0-9]+)(\+.+)?$ ]]; then
          echo "::error::Version does not match supported pattern: $VERSION"
          echo "::error::Expected format: [v]X.Y.Z[+postfix]"
          exit 1
        fi

        # Extract components for version-short
        if [[ "$VERSION" =~ ^([vV]?)([0-9]+\.[0-9]+\.[0-9]+)(\+.+)?$ ]]; then
          VERSION_SHORT="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
        else
          VERSION_SHORT="$VERSION"
        fi

        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        echo "version_short=$VERSION_SHORT" >> "$GITHUB_OUTPUT"

        echo "::notice::Version: $VERSION"
        echo "::notice::Version Short: $VERSION_SHORT"

        {
          echo "### version-reader"
          echo "- CI tag source: $TYPE"
          if [[ "$TYPE" == "branch" ]]; then
            echo "- Branch: $BRANCH"
          fi
          echo "- Version: $VERSION"
          echo "- Version Short: $VERSION_SHORT"
        } >> "$GITHUB_STEP_SUMMARY"
