name: docker-tag-builder
description: Build Docker image tags based on version and latest version detection

inputs:
  version:
    description: "Version to tag (e.g., v1.2.12, 1.2.12). Required for major/minor/patch levels."
    required: false
  is-latest-version:
    description: "Whether this is the latest version globally (true/false)"
    required: true
  tag-levels:
    description: "Tag levels: patch, minor, major, latest, or custom tags (e.g., sha, edge, beta). Comma-separated."
    required: false
    default: 'patch'
  git-tag-levels:
    description: "Git tag levels (optional). When provided, validates that semantic docker tag levels are subset of git tag levels."
    required: false
  ci-tag-source:
    description: "Version source type (nodejs, flutter, branch). Validation only enforced when set to 'branch'."
    required: false
    default: ''

outputs:
  docker-tags:
    description: "Space-separated list of Docker tags"
    value: ${{ steps.build.outputs.docker_tags }}
  exact-tag:
    description: "Exact version tag (e.g., v1.2.12)"
    value: ${{ steps.build.outputs.exact_tag }}
  latest-tag:
    description: "Latest tag (latest), empty if not created"
    value: ${{ steps.build.outputs.latest_tag }}

runs:
  using: "composite"
  steps:
    - name: Validate tag level consistency
      shell: bash
      run: |
        set -euo pipefail

        DOCKER_LEVELS="${{ inputs.tag-levels }}"
        GIT_LEVELS="${{ inputs.git-tag-levels }}"
        CI_TAG_SOURCE="${{ inputs.ci-tag-source }}"

        if [ "$CI_TAG_SOURCE" != "branch" ]; then
          echo "::notice::ci-tag-source is '$CI_TAG_SOURCE' (not 'branch'), skipping consistency validation"
          exit 0
        fi

        IFS=',' read -ra DOCKER_ARRAY <<< "$DOCKER_LEVELS"

        for level in "${DOCKER_ARRAY[@]}"; do
          level=$(echo "$level" | xargs)

          if [[ "$level" == "patch" || "$level" == "minor" || "$level" == "major" ]]; then
            if [[ ! "$GIT_LEVELS" =~ (^|,)$level(,|$) ]]; then
              echo "::error::Docker tag level '$level' must be included in git-tag-levels to maintain version consistency."
              echo "::error::Current docker tag-levels: $DOCKER_LEVELS"
              echo "::error::Current git-tag-levels: $GIT_LEVELS"
              echo "::error::Fix: Add '$level' to git-tag-levels (e.g., git-tag-levels: '$level' or git-tag-levels: 'patch,minor,major')"
              exit 1
            fi
          fi
        done

        echo "::notice::Tag level consistency validated successfully"

    - name: Build Docker tags
      id: build
      shell: bash
      run: |
        set -euo pipefail

        VERSION="${{ inputs.version }}"
        IS_LATEST="${{ inputs.is-latest-version }}"
        TAG_LEVELS="${{ inputs.tag-levels }}"

        PREFIX=""
        MAJOR=""
        MINOR=""
        PATCH=""
        EXACT_TAG=""

        if [ -n "$VERSION" ]; then
          if [[ ! "$VERSION" =~ ^([vV]?)([0-9]+)\.([0-9]+)\.([0-9]+)(\+.+)?$ ]]; then
            echo "::error::Invalid version format: $VERSION"
            echo "::error::Expected format: [v]X.Y.Z[+postfix]"
            exit 1
          fi

          PREFIX="${BASH_REMATCH[1]}"
          MAJOR="${BASH_REMATCH[2]}"
          MINOR="${BASH_REMATCH[3]}"
          PATCH="${BASH_REMATCH[4]}"

          EXACT_TAG="${PREFIX}${MAJOR}.${MINOR}.${PATCH}"
        fi

        DOCKER_TAGS=""

        IFS=',' read -ra LEVELS <<< "$TAG_LEVELS"
        for level in "${LEVELS[@]}"; do
          level=$(echo "$level" | xargs)

          case "$level" in
            patch)
              if [ -z "$VERSION" ]; then
                echo "::error::Version required for 'patch' tag level"
                exit 1
              fi
              if [ -z "$DOCKER_TAGS" ]; then
                DOCKER_TAGS="$EXACT_TAG"
              else
                DOCKER_TAGS="$DOCKER_TAGS $EXACT_TAG"
              fi
              echo "::notice::Adding patch-level tag: $EXACT_TAG"
              ;;
            minor)
              if [ -z "$VERSION" ]; then
                echo "::error::Version required for 'minor' tag level"
                exit 1
              fi
              if [ -z "$DOCKER_TAGS" ]; then
                DOCKER_TAGS="${PREFIX}${MAJOR}.${MINOR}"
              else
                DOCKER_TAGS="$DOCKER_TAGS ${PREFIX}${MAJOR}.${MINOR}"
              fi
              echo "::notice::Adding minor-level tag: ${PREFIX}${MAJOR}.${MINOR}"
              ;;
            major)
              if [ -z "$VERSION" ]; then
                echo "::error::Version required for 'major' tag level"
                exit 1
              fi
              if [ -z "$DOCKER_TAGS" ]; then
                DOCKER_TAGS="${PREFIX}${MAJOR}"
              else
                DOCKER_TAGS="$DOCKER_TAGS ${PREFIX}${MAJOR}"
              fi
              echo "::notice::Adding major-level tag: ${PREFIX}${MAJOR}"
              ;;
            latest)
              if [[ "$IS_LATEST" == "true" ]]; then
                if [ -z "$DOCKER_TAGS" ]; then
                  DOCKER_TAGS="latest"
                else
                  DOCKER_TAGS="$DOCKER_TAGS latest"
                fi
                echo "::notice::Adding latest tag: latest"
              else
                echo "::notice::Not the latest version globally, skipping :latest tag"
              fi
              ;;
            *)
              if [ -z "$DOCKER_TAGS" ]; then
                DOCKER_TAGS="$level"
              else
                DOCKER_TAGS="$DOCKER_TAGS $level"
              fi
              echo "::notice::Adding custom tag: $level"
              ;;
          esac
        done

        if [ -z "$DOCKER_TAGS" ]; then
          echo "::error::No tags generated"
          exit 1
        fi

        LATEST_TAG=""
        if [[ "$DOCKER_TAGS" =~ (^| )latest( |$) ]]; then
          LATEST_TAG="latest"
        fi

        echo "exact_tag=$EXACT_TAG" >> "$GITHUB_OUTPUT"
        echo "latest_tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"
        echo "docker_tags=$DOCKER_TAGS" >> "$GITHUB_OUTPUT"

        echo "::notice::Docker tags: $DOCKER_TAGS"

        {
          echo "### docker-tag-builder"
          echo "- Version: \`${VERSION:-none}\`"
          echo "- Is latest version: \`$IS_LATEST\`"
          echo "- Tag levels: \`$TAG_LEVELS\`"
          echo "- Calculated docker tags:"
          for tag in $DOCKER_TAGS; do
            echo "  - \`$tag\`"
          done
        } >> "$GITHUB_STEP_SUMMARY"
