name: git-tag-builder
description: Create git tags based on version and target branch with optional branch-level tagging

inputs:
  version:
    description: "Version to tag (e.g., v1.2.12, 1.2.12)"
    required: true
  target-branch:
    description: "Target branch name (e.g., main, v1.2, develop)"
    required: true
  enable-branch-tag:
    description: "Enable branch-level tagging when branch name is version-like (default: true)"
    required: false
    default: 'true'

outputs:
  git-tags:
    description: "List of git tags created (space-separated)"
    value: ${{ steps.tag.outputs.git_tags }}
  exact-tag:
    description: "Exact version tag created (e.g., v1.2.12)"
    value: ${{ steps.tag.outputs.exact_tag }}
  branch-tag:
    description: "Branch-level tag created (e.g., v1.2), empty if not created"
    value: ${{ steps.tag.outputs.branch_tag }}

runs:
  using: "composite"
  steps:
    - name: Parse version and create tags
      id: tag
      shell: bash
      run: |
        set -euo pipefail

        VERSION="${{ inputs.version }}"
        TARGET_BRANCH="${{ inputs.target-branch }}"
        ENABLE_BRANCH_TAG="${{ inputs.enable-branch-tag }}"

        # Validate version format
        if [[ ! "$VERSION" =~ ^([vV]?)([0-9]+)\.([0-9]+)\.([0-9]+)(\+.+)?$ ]]; then
          echo "::error::Invalid version format: $VERSION"
          echo "::error::Expected format: [v]X.Y.Z[+postfix]"
          exit 1
        fi

        PREFIX="${BASH_REMATCH[1]}"
        MAJOR="${BASH_REMATCH[2]}"
        MINOR="${BASH_REMATCH[3]}"
        PATCH="${BASH_REMATCH[4]}"
        POSTFIX="${BASH_REMATCH[5]}"

        # Strip postfix for tagging (git tags should be clean semver)
        EXACT_TAG="${PREFIX}${MAJOR}.${MINOR}.${PATCH}"

        echo "::notice::Creating exact version tag: $EXACT_TAG"

        # Create exact version tag
        if git rev-parse "$EXACT_TAG" >/dev/null 2>&1; then
          echo "::error::Tag $EXACT_TAG already exists"
          exit 1
        fi

        git tag "$EXACT_TAG"
        TAGS_CREATED="$EXACT_TAG"

        # Determine if we should create a branch-level tag
        BRANCH_TAG=""
        if [[ "$ENABLE_BRANCH_TAG" == "true" ]]; then
          # Check if target branch name is version-like (e.g., v1.2, 1.2, v1)
          if [[ "$TARGET_BRANCH" =~ ^([vV]?)([0-9]+)\.([0-9]+)$ ]]; then
            # Branch is major.minor format (e.g., v1.2)
            BRANCH_PREFIX="${BASH_REMATCH[1]}"
            BRANCH_MAJOR="${BASH_REMATCH[2]}"
            BRANCH_MINOR="${BASH_REMATCH[3]}"
            BRANCH_TAG="${BRANCH_PREFIX}${BRANCH_MAJOR}.${BRANCH_MINOR}"

            # Only create branch tag if it matches current version's major.minor
            if [ "$BRANCH_MAJOR" == "$MAJOR" ] && [ "$BRANCH_MINOR" == "$MINOR" ]; then
              echo "::notice::Creating branch-level tag: $BRANCH_TAG"

              # Delete existing branch tag if it exists (we're updating it)
              if git rev-parse "$BRANCH_TAG" >/dev/null 2>&1; then
                echo "::notice::Updating existing branch tag: $BRANCH_TAG"
                git tag -d "$BRANCH_TAG" >/dev/null 2>&1 || true
                git push origin ":refs/tags/$BRANCH_TAG" >/dev/null 2>&1 || true
              fi

              git tag "$BRANCH_TAG"
              TAGS_CREATED="$TAGS_CREATED $BRANCH_TAG"
            else
              echo "::notice::Branch version ($BRANCH_MAJOR.$BRANCH_MINOR) does not match current version ($MAJOR.$MINOR), skipping branch tag"
            fi
          elif [[ "$TARGET_BRANCH" =~ ^([vV]?)([0-9]+)$ ]]; then
            # Branch is major-only format (e.g., v1)
            BRANCH_PREFIX="${BASH_REMATCH[1]}"
            BRANCH_MAJOR="${BASH_REMATCH[2]}"
            BRANCH_TAG="${BRANCH_PREFIX}${BRANCH_MAJOR}"

            # Only create branch tag if it matches current version's major
            if [ "$BRANCH_MAJOR" == "$MAJOR" ]; then
              echo "::notice::Creating branch-level tag: $BRANCH_TAG"

              # Delete existing branch tag if it exists (we're updating it)
              if git rev-parse "$BRANCH_TAG" >/dev/null 2>&1; then
                echo "::notice::Updating existing branch tag: $BRANCH_TAG"
                git tag -d "$BRANCH_TAG" >/dev/null 2>&1 || true
                git push origin ":refs/tags/$BRANCH_TAG" >/dev/null 2>&1 || true
              fi

              git tag "$BRANCH_TAG"
              TAGS_CREATED="$TAGS_CREATED $BRANCH_TAG"
            else
              echo "::notice::Branch version ($BRANCH_MAJOR) does not match current version ($MAJOR), skipping branch tag"
            fi
          else
            echo "::notice::Branch name '$TARGET_BRANCH' is not version-like, skipping branch tag"
          fi
        fi

        echo "exact_tag=$EXACT_TAG" >> "$GITHUB_OUTPUT"
        echo "branch_tag=$BRANCH_TAG" >> "$GITHUB_OUTPUT"
        echo "git_tags=$TAGS_CREATED" >> "$GITHUB_OUTPUT"

        {
          echo "### git-tag-builder"
          echo "- Target branch: $TARGET_BRANCH"
          echo "- Exact tag: $EXACT_TAG"
          if [ -n "$BRANCH_TAG" ]; then
            echo "- Branch tag: $BRANCH_TAG"
          fi
          echo "- Tags created: $TAGS_CREATED"
        } >> "$GITHUB_STEP_SUMMARY"
