name: node-js-patch-package
description: Update package.json version with supplied semver.

outputs:
  updated_version:
    description: "Version written to package.json"
    value: ${{ steps.patch.outputs.updated_version }}
  git_next_tag:
    description: "Next git tag including prefix"
    value: ${{ steps.tags.outputs.next_tag }}
  git_next_tag_short:
    description: "Next git tag without prefix"
    value: ${{ steps.tags.outputs.next_tag_short }}

runs:
  using: "composite"
  steps:
    - name: Tag calculation
      id: tags
      uses: draftm0de/github.workflows/.github/actions/node-js-version-builder@main

    - name: Update package.json version
      id: patch
      shell: bash
      run: |
        set -euo pipefail

        FILE="${{ inputs.package-json-path }}"
        VERSION="${{ inputs.new-version }}"

        if [ ! -f "$FILE" ]; then
          echo "::error::package.json not found at $FILE"
          exit 1
        fi

        if ! echo "$VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+(\+[A-Za-z0-9.-]+)?$'; then
          echo "::error::new-version must be x.y.z with optional +build"
          exit 1
        fi

        node <<'NODE' "$FILE" "$VERSION"
const fs = require('node:fs');
const manifestPath = process.argv[1];
const newVersion = process.argv[2];
const data = fs.readFileSync(manifestPath, 'utf8');
const pkg = JSON.parse(data);
pkg.version = newVersion;
fs.writeFileSync(manifestPath, JSON.stringify(pkg, null, 2) + '\n');
NODE

        echo "updated_version=$VERSION" >> "$GITHUB_OUTPUT"
        {
          echo "### node-js-patch-package"
          echo "- Updated $FILE to $VERSION"
        } >> "$GITHUB_STEP_SUMMARY"

    - name: Commit version update
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -am "chore: release ${{ steps.tags.outputs.next_tag }}"
