name: docker-push
description: Push Docker image to registry with multiple tags

inputs:
  image:
    description: "Local Docker image name to push"
    required: true
  tags:
    description: "Space-separated list of tags to push (e.g., 'v1.2.12 v1.2 latest')"
    required: true
  registry:
    description: "Registry hostname (e.g., 'ghcr.io', leave blank for Docker Hub)"
    required: false
  username:
    description: "Registry username (inferred from first tag if not provided)"
    required: false
  password:
    description: "Registry password or token"
    required: true

outputs:
  tags-pushed:
    description: "Space-separated list of fully-qualified tags that were pushed"
    value: ${{ steps.push.outputs.tags_pushed }}

runs:
  using: "composite"
  steps:
    - name: Workflow Setup
      id: setup
      shell: bash
      run: |
        set -euo pipefail

        IMAGE="${{ inputs.image }}"
        TAGS="${{ inputs.tags }}"
        USERNAME="${{ inputs.username }}"
        PASSWORD="${{ inputs.password }}"

        if [ -z "$IMAGE" ]; then
          echo "::error::Input 'image' is required"
          exit 1
        fi

        if [ -z "$TAGS" ]; then
          echo "::error::Input 'tags' is required"
          exit 1
        fi

        if [ -z "$PASSWORD" ]; then
          echo "::error::Input 'password' is required"
          exit 1
        fi

        if ! docker inspect --type=image "$IMAGE" >/dev/null 2>&1; then
          echo "::error::Image '$IMAGE' not found locally"
          exit 1
        fi

        if [ -z "$USERNAME" ]; then
          if [[ "$IMAGE" =~ ^([^/]+)/(.+)$ ]]; then
            USERNAME="${BASH_REMATCH[1]}"
            IMAGE="${BASH_REMATCH[2]}"
            echo "::notice::extracted username from image name: $USERNAME"
          else
            echo "::error::Cannot infer username from image name '$IMAGE'. Please provide 'username' input."
            exit 1
          fi
        else
          echo "::notice::Using provided username: $USERNAME"
        fi

        if [[ "$IMAGE" == *":"* ]]; then
          IMAGE="${IMAGE%%:*}"
          echo "::notice::Stripped tag from image name: $IMAGE"
        fi

        echo "username=$USERNAME" >> "$GITHUB_OUTPUT"
        echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
        echo "::notice::Validated image: $IMAGE"
        echo "::notice::Tags to push: $TAGS"

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ steps.setup.outputs.username }}
        password: ${{ inputs.password }}

    - name: Push Docker image
      id: push
      shell: bash
      run: |
        set -euo pipefail

        SOURCE_IMAGE="${{ inputs.image }}"
        IMAGE="${{ steps.setup.outputs.image }}"
        TAGS="${{ inputs.tags }}"
        REGISTRY="${{ inputs.registry }}"
        USERNAME="${{ steps.setup.outputs.username }}"

        PUSHED_TAGS=""

        for tag in $TAGS; do
          if [ -n "$REGISTRY" ]; then
            FULL_TAG="$REGISTRY/$USERNAME/$IMAGE:$tag"
          else
            FULL_TAG="$USERNAME/$IMAGE:$tag"
          fi

          echo "::notice::Tagging $SOURCE_IMAGE as $FULL_TAG"
          docker tag "$SOURCE_IMAGE" "$FULL_TAG"

          echo "::notice::Pushing $FULL_TAG"
          docker push "$FULL_TAG"

          if [ -z "$PUSHED_TAGS" ]; then
            PUSHED_TAGS="$FULL_TAG"
          else
            PUSHED_TAGS="$PUSHED_TAGS $FULL_TAG"
          fi
        done

        echo "tags_pushed=$PUSHED_TAGS" >> "$GITHUB_OUTPUT"

        {
          echo "### docker-push"
          echo "- Source image: \`$SOURCE_IMAGE\`"
          echo "- Registry: \`${REGISTRY:-Docker Hub}\`"
          echo "- Tags pushed:"
          for tag in $PUSHED_TAGS; do
            echo "  - \`$tag\`"
          done
        } >> "$GITHUB_STEP_SUMMARY"
