name: docker-push
description: Push Docker image to registry with multiple tags

inputs:
  image:
    description: "Local Docker image name to push"
    required: true
  tags:
    description: "Comma-separated list of tags to push (e.g., 'v1.2.12,v1.2,latest')"
    required: true
  registry:
    description: "Registry hostname (e.g., 'ghcr.io', leave blank for Docker Hub)"
    required: false
  username:
    description: "Registry username (inferred from first tag if not provided)"
    required: false
  password:
    description: "Registry password or token"
    required: true

outputs:
  tags-pushed:
    description: "Comma-separated list of fully-qualified tags that were pushed"
    value: ${{ steps.push.outputs.tags_pushed }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      id: validate
      shell: bash
      run: |
        set -euo pipefail

        IMAGE="${{ inputs.image }}"
        TAGS="${{ inputs.tags }}"

        if [ -z "$IMAGE" ]; then
          echo "::error::Input 'image' is required"
          exit 1
        fi

        if [ -z "$TAGS" ]; then
          echo "::error::Input 'tags' is required"
          exit 1
        fi

        if ! docker inspect --type=image "$IMAGE" >/dev/null 2>&1; then
          echo "::error::Image '$IMAGE' not found locally"
          exit 1
        fi

        echo "::notice::Validated image: $IMAGE"
        echo "::notice::Tags to push: $TAGS"

    - name: Determine registry username
      id: username
      shell: bash
      run: |
        set -euo pipefail

        USERNAME="${{ inputs.username }}"
        TAGS="${{ inputs.tags }}"

        if [ -z "$USERNAME" ]; then
          FIRST_TAG=$(echo "$TAGS" | cut -d',' -f1 | xargs)
          if [[ "$FIRST_TAG" =~ ^([^/]+)/.*$ ]]; then
            USERNAME="${BASH_REMATCH[1]}"
            echo "::notice::Inferred username from first tag: $USERNAME"
          else
            echo "::error::Cannot infer username from tag '$FIRST_TAG'. Please provide 'username' input."
            exit 1
          fi
        else
          echo "::notice::Using provided username: $USERNAME"
        fi

        echo "username=$USERNAME" >> "$GITHUB_OUTPUT"

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ steps.username.outputs.username }}
        password: ${{ inputs.password }}

    - name: Push Docker image
      id: push
      shell: bash
      run: |
        set -euo pipefail

        IMAGE="${{ inputs.image }}"
        TAGS="${{ inputs.tags }}"
        REGISTRY="${{ inputs.registry }}"

        PUSHED_TAGS=""

        IFS=',' read -ra TAG_ARRAY <<< "$TAGS"
        for tag in "${TAG_ARRAY[@]}"; do
          tag=$(echo "$tag" | xargs)

          if [ -n "$REGISTRY" ]; then
            FULL_TAG="$REGISTRY/$tag"
          else
            FULL_TAG="$tag"
          fi

          echo "::notice::Tagging $IMAGE as $FULL_TAG"
          docker tag "$IMAGE" "$FULL_TAG"

          echo "::notice::Pushing $FULL_TAG"
          docker push "$FULL_TAG"

          if [ -z "$PUSHED_TAGS" ]; then
            PUSHED_TAGS="$FULL_TAG"
          else
            PUSHED_TAGS="$PUSHED_TAGS,$FULL_TAG"
          fi
        done

        echo "tags_pushed=$PUSHED_TAGS" >> "$GITHUB_OUTPUT"

        {
          echo "### docker-push"
          echo "- Source image: \`$IMAGE\`"
          echo "- Registry: \`${REGISTRY:-Docker Hub}\`"
          echo "- Tags pushed:"
          IFS=',' read -ra PUSHED_ARRAY <<< "$PUSHED_TAGS"
          for pushed in "${PUSHED_ARRAY[@]}"; do
            echo "  - \`$pushed\`"
          done
        } >> "$GITHUB_STEP_SUMMARY"
